[package]
name = "rustset-ai-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rustset-framework-tenant.workspace = true
async-trait.workspace = true
axum.workspace = true
aide.workspace = true
schemars.workspace = true
base64.workspace = true
chrono.workspace = true
futures-util.workspace = true
reqwest.workspace = true
rustset-ai-api.workspace = true
rustset-framework-common.workspace = true
rustset-framework-database.workspace = true
rustset-framework-security.workspace = true
rustset-framework-web.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true

[dev-dependencies]
aide.workspace = true
http-body-util = "0.1"
tower.workspace = true
