[package]
name = "rustset-infra-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aws-sdk-s3.workspace = true
axum.workspace = true
aide.workspace = true
schemars.workspace = true
base64.workspace = true
chrono.workspace = true
rustset-framework-common.workspace = true
rustset-framework-database.workspace = true
rustset-framework-security.workspace = true
rustset-framework-tofu.workspace = true
rustset-framework-gm.workspace = true
tracing.workspace = true
rustset-framework-web.workspace = true
rustset-infra-api.workspace = true
rustset-cmdb-api.workspace = true
rust_xlsxwriter.workspace = true
redis.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true
zip.workspace = true
