[package]
name = "rustset-cmdb-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rustset-framework-tenant.workspace = true
axum.workspace = true
aide.workspace = true
schemars.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
rustset-cmdb-api.workspace = true
rustset-framework-common.workspace = true
rustset-framework-database.workspace = true
rustset-framework-security.workspace = true
rustset-framework-web.workspace = true

[dev-dependencies]
tokio.workspace = true
tower.workspace = true
