CREATE TABLE IF NOT EXISTS public.cmdb_attribute_trigger (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id bigint NOT NULL,
    name varchar(128) NOT NULL,
    condition_code varchar(64) NOT NULL,
    condition_value jsonb NOT NULL,
    action_code varchar(64) NOT NULL,
    action_value jsonb NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    creator varchar(64) NOT NULL DEFAULT '',
    updater varchar(64) NOT NULL DEFAULT '',
    create_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_cmdb_attribute_trigger_model
    ON public.cmdb_attribute_trigger (model_id) WHERE deleted = 0;
